jenkins:
  image: iliyan/jenkins-ci-php
  container_name: jenkins-php
  ports:
    - "8000"
    - "8080"
  volumes:
    - ~/projects:/code
    - ./data:/var/lib/jenkins
    - ./setup.sh:/setup.sh
  restart: always
